### PR TITLE
Created Code_of_Conduct and License

### PR DESCRIPTION
**Pull request by ARRY7686**
Created CODE_OF_CONDUCT AND LICENSE as per instructed

### CODE REVIEW

**Comment by ARRY7686** [comment]
@mohitahlawat2001 created both of the files for you kindly check and merge both the PRs

**Comment by ARRY7686** [comment]
@mohitahlawat2001 pls check and tell if it needs any improvement if not merge it with the codebase

**Comment by ARRY7686** [comment]
#5 #3

**Comment by mohitahlawat2001** [comment]
make single pr

**Pull request closed without merging**
