### PR TITLE
Fixed login button alignment on Login page and background opacity

### PR DESCRIPTION
**Pull request by Jai-Marothiya**
# Description

* Fixed login button alignment on Login page and background opacity

## Before
image

## After
image

### CODE REVIEW

**Comment by mohitahlawat2001** [comment]
post photo before and after change

**Comment by Jai-Marothiya** [comment]
> post photo before and after change

I attached the images

**Comment by Jai-Marothiya** [comment]
@mohitahlawat2001 - could you please add Hacktoberfest label in this PR and issue.

**Comment by mohitahlawat2001** [comment]
did you read instruction when i assigned you issue?

@Jai-Marothiya  i mention something related to this 

> could you please add Hacktoberfest label in this PR and issue.

**Comment by Jai-Marothiya** [comment]
> did you read instruction when i assigned you issue?
> 
> @Jai-Marothiya i mention something related to this
> 
> > could you please add Hacktoberfest label in this PR and issue.

@mohitahlawat2001 I stared your repo.

**Comment by aakarsh-2004** [comment]
Did this PR count towards the hacktoberfest @Jai-Marothiya?

**Comment by mohitahlawat2001** [comment]
@aakarsh-2004 totally depend on hacktoberfest reviewer

**Pull request merged**
