### PR TITLE
Fix:Improvement in .env Setup Instructions for Firebase and Other API Keys

### PR DESCRIPTION
**Pull request by ARRY7686**
### Description:
This PR addresses an issue in the documentation related to setting up environment variables for Firebase integration. The previous documentation only included a subset of the required fields for Firebase functionality, which could result in incomplete configurations and potential errors when using services like Cloud Messaging, Analytics, and Storage.

The following Firebase-specific environment variables have been added to the .env setup instructions:
```
REACT_APP_FIREBASE_PROJECT_ID
REACT_APP_FIREBASE_STORAGE_BUCKET
REACT_APP_FIREBASE_MESSAGING_SENDER_ID
REACT_APP_FIREBASE_APP_ID
REACT_APP_FIREBASE_MEASUREMENT_ID
```
This ensures that users setting up Firebase within the project will have the full set of necessary fields for a smooth and complete integration.

### Changes:
Updated documentation to include the missing Firebase environment variables.
Clarified instructions for configuring the .env file for Firebase services.
Issue Reference:
This PR resolves the issue of missing Firebase fields in the environment setup, which was noted during a review of the current documentation.

###Fixes:
This PR fixes issue #3 
### Contribution:
As part of my participation in Hacktoberfest, I am contributing this fix to ensure others have a smoother experience setting up their environment. Thank you for the opportunity!

### CODE REVIEW

**Review by mohitahlawat2001 — COMMENTED** [review]
if possible add these file also
Code of conduct,
 Contributing,

 License

**Comment by ARRY7686** [comment]
pls merge this request i will create a new issue and add those files there
as this issue is related to env file and changes in it

**Comment by mohitahlawat2001** [comment]
i merge it now , if might label as spam by hacktoberfest reviewer team , you can added here , other i will close this pr

**Comment by ARRY7686** [comment]
its not possible right now for me as It requires a specific template and other things that should be approved by the maintainer and can only be done by the maintainer

**Comment by ARRY7686** [comment]
If you want any other changes with the readme I can help you with that

**Comment by ARRY7686** [comment]
I am writing all the files requested give me some time

**Comment by ARRY7686** [comment]
@mohitahlawat2001 can you pls provide me ur email adress as it is needed in code of conduct

**Comment by mohitahlawat2001** [comment]
email : mohitahlawat.2001.ma@gmail.com

**Comment by mohitahlawat2001** [comment]
make single pr

**Pull request closed without merging**
