### PR TITLE
Pre-built queries

### PR DESCRIPTION
**Pull request by memyselfandglitch**
Added the option to click on pre-built queries that would send a post request to LLM directly. Below are the results 
Screenshot 2024-10-01 at 00 25 58
Screenshot 2024-10-01 at 00 25 41

### CODE REVIEW

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
write these query in this file  with different language

> ./src/utils/languageConstants.js


and import label and query  in below file from above file

> ./src/components/AniSearchBar.js


so that it become shown in different language 

also need to improve these query quality , its look like simple sentence

**Comment by memyselfandglitch** [comment]
Alright noted. As per my understanding I should fetch the pre-build queries from languageConstants.js file and improve the query quality. Below are the screenshots of the new changes. Let me know if this was what you had in mind or I should make any further changes. 
Screenshot 2024-10-01 at 16 58 20
Screenshot 2024-10-01 at 16 58 02

**Review by mohitahlawat2001 — APPROVED** [review]
Thank you for contribution

**Comment by mohitahlawat2001** [comment]
did you star the repo , in case didnt do please do!

**Pull request merged**
